import sys

def main():
    files = [
        'lib/services/jamakkol_one_page_pdf_service.dart',
        'lib/services/kp_one_page_pdf_service.dart',
        'lib/services/marriage_matching_pdf_service.dart',
        'lib/services/report_html_service.dart'
    ]

    for file_path in files:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            new_content = content.replace("Created by Aadhiguru Astrology Software", "Created by Aadhiguru Astrology Software | Mobile: +91 96006 66225")
            new_content = new_content.replace("Generated by Aadhiguru Astrology Software", "Generated by Aadhiguru Astrology Software | Mobile: +91 96006 66225")
            
            # Special case for report_html_service.dart which has a different footer format
            if 'report_html_service.dart' in file_path:
                new_content = new_content.replace(
                    '<div class="footer">\n          <p>This report was generated using Aadhiguru Astrology Software.</p>\n        </div>',
                    '<div class="footer">\n          <p>This report was generated using Aadhiguru Astrology Software. Mobile: +91 96006 66225</p>\n        </div>'
                )

            if new_content != content:
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(new_content)
                print(f"Updated {file_path}")
            else:
                print(f"No match found in {file_path}")
                
        except Exception as e:
            print(f"Error processing {file_path}: {e}")

if __name__ == '__main__':
    main()
